language: ruby
rvm:
- 2.1.5
script:
- git submodule update --init
- BUNDLE_GEMFILE=cf.Gemfile bundle install
- BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager cached
- mv ./*.zip php-buildpack-offline.zip
- ls -la
deploy:
  provider: releases
  api_key:
    secure: E0r8SC4yVJqkHlv+HwTAanLxFDq+8nlPGNQKWcS+dNPnneb+G121J6zJpt67M/PTiXkCdOGTzEyzk20nW/BD6ZgTcSQPpe8ulkNOCyurKt2Dhf72mx4jIa8IaODccWE0luT4gckwFHVa4/fOn6MH7aDhweOsTKCinbHadZafugg=
  file: php-buildpack-offline.zip
  on:
    tags: true
    all_branches: true
