language: ruby
rvm:
- 2.1.5
script:
- git submodule update --init
- BUNDLE_GEMFILE=cf.Gemfile bundle install
- BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager cached
- mv ./*.zip php-buildpack-offline.zip
- ls -la
deploy:
  provider: releases
  user: ArthurHlt
  file: php-buildpack-offline.zip
  on:
    tags: true
    all_branches: true
  password:
    secure: knSYETz8xHwnTUdk4MDIou1Ne1FGckRG5eACegDC/UbIjSRABwS0+YDT5wpf0xrY+9u8tLJxV4NwW45Iavb2WUPZUmvlQDgS/BSOYU0wc9qgZmiF6OKgkkAJeE0nWyI4HbNEVwB+zXLE2QGmtrfZIgBa3nA2B7xT1+WdTDCNsKI=
