<?php

namespace ContainerAmCHZM2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HSp4x7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._HSp4x7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._HSp4x7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\BlogController::delete' => ['privates', '.service_locator.vEgYHnL', 'get_ServiceLocator_VEgYHnLService', true],
            'App\\Controller\\Admin\\BlogController::edit' => ['privates', '.service_locator.vEgYHnL', 'get_ServiceLocator_VEgYHnLService', true],
            'App\\Controller\\Admin\\BlogController::index' => ['privates', '.service_locator.yDGDnoA', 'get_ServiceLocator_YDGDnoAService', true],
            'App\\Controller\\Admin\\BlogController::show' => ['privates', '.service_locator.vEgYHnL', 'get_ServiceLocator_VEgYHnLService', true],
            'App\\Controller\\BlogController::commentForm' => ['privates', '.service_locator.vEgYHnL', 'get_ServiceLocator_VEgYHnLService', true],
            'App\\Controller\\BlogController::commentNew' => ['privates', '.service_locator.Qe2gjou', 'get_ServiceLocator_Qe2gjouService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.B1TQNMP', 'get_ServiceLocator_B1TQNMPService', true],
            'App\\Controller\\BlogController::postShow' => ['privates', '.service_locator.vEgYHnL', 'get_ServiceLocator_VEgYHnLService', true],
            'App\\Controller\\BlogController::search' => ['privates', '.service_locator.yDGDnoA', 'get_ServiceLocator_YDGDnoAService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.usL6piz', 'get_ServiceLocator_UsL6pizService', true],
            'App\\Controller\\UserController::changePassword' => ['privates', '.service_locator.wxjqEW2', 'get_ServiceLocator_WxjqEW2Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel::terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
            'App\\Controller\\Admin\\BlogController:delete' => ['privates', '.service_locator.vEgYHnL', 'get_ServiceLocator_VEgYHnLService', true],
            'App\\Controller\\Admin\\BlogController:edit' => ['privates', '.service_locator.vEgYHnL', 'get_ServiceLocator_VEgYHnLService', true],
            'App\\Controller\\Admin\\BlogController:index' => ['privates', '.service_locator.yDGDnoA', 'get_ServiceLocator_YDGDnoAService', true],
            'App\\Controller\\Admin\\BlogController:show' => ['privates', '.service_locator.vEgYHnL', 'get_ServiceLocator_VEgYHnLService', true],
            'App\\Controller\\BlogController:commentForm' => ['privates', '.service_locator.vEgYHnL', 'get_ServiceLocator_VEgYHnLService', true],
            'App\\Controller\\BlogController:commentNew' => ['privates', '.service_locator.Qe2gjou', 'get_ServiceLocator_Qe2gjouService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.B1TQNMP', 'get_ServiceLocator_B1TQNMPService', true],
            'App\\Controller\\BlogController:postShow' => ['privates', '.service_locator.vEgYHnL', 'get_ServiceLocator_VEgYHnLService', true],
            'App\\Controller\\BlogController:search' => ['privates', '.service_locator.yDGDnoA', 'get_ServiceLocator_YDGDnoAService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.usL6piz', 'get_ServiceLocator_UsL6pizService', true],
            'App\\Controller\\UserController:changePassword' => ['privates', '.service_locator.wxjqEW2', 'get_ServiceLocator_WxjqEW2Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel:terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
        ], [
            'App\\Controller\\Admin\\BlogController::delete' => '?',
            'App\\Controller\\Admin\\BlogController::edit' => '?',
            'App\\Controller\\Admin\\BlogController::index' => '?',
            'App\\Controller\\Admin\\BlogController::show' => '?',
            'App\\Controller\\BlogController::commentForm' => '?',
            'App\\Controller\\BlogController::commentNew' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::postShow' => '?',
            'App\\Controller\\BlogController::search' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::changePassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\BlogController:delete' => '?',
            'App\\Controller\\Admin\\BlogController:edit' => '?',
            'App\\Controller\\Admin\\BlogController:index' => '?',
            'App\\Controller\\Admin\\BlogController:show' => '?',
            'App\\Controller\\BlogController:commentForm' => '?',
            'App\\Controller\\BlogController:commentNew' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:postShow' => '?',
            'App\\Controller\\BlogController:search' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:changePassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
