<?php

namespace ContainerAmCHZM2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Qe2gjou.App\Entity\Post' shared service.
     *
     * @return \App\Entity\Post
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Qe2gjou": it references class "App\\Entity\\Post" but no such service exists.');
    }
}
