<?php

namespace ContainerFelbUiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HM478IFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hM478IF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hM478IF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\BlogController::delete' => ['privates', '.service_locator.A2a9FbN', 'get_ServiceLocator_A2a9FbNService', true],
            'App\\Controller\\Admin\\BlogController::edit' => ['privates', '.service_locator.A2a9FbN', 'get_ServiceLocator_A2a9FbNService', true],
            'App\\Controller\\Admin\\BlogController::index' => ['privates', '.service_locator.3Q_vHjc', 'get_ServiceLocator_3QVHjcService', true],
            'App\\Controller\\Admin\\BlogController::show' => ['privates', '.service_locator.A2a9FbN', 'get_ServiceLocator_A2a9FbNService', true],
            'App\\Controller\\BlogController::commentForm' => ['privates', '.service_locator.A2a9FbN', 'get_ServiceLocator_A2a9FbNService', true],
            'App\\Controller\\BlogController::commentNew' => ['privates', '.service_locator.Sd9SChb', 'get_ServiceLocator_Sd9SChbService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.DXcXSsX', 'get_ServiceLocator_DXcXSsXService', true],
            'App\\Controller\\BlogController::postShow' => ['privates', '.service_locator.A2a9FbN', 'get_ServiceLocator_A2a9FbNService', true],
            'App\\Controller\\BlogController::search' => ['privates', '.service_locator.3Q_vHjc', 'get_ServiceLocator_3QVHjcService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.IKb2hHY', 'get_ServiceLocator_IKb2hHYService', true],
            'App\\Controller\\UserController::changePassword' => ['privates', '.service_locator.1d_X9dd', 'get_ServiceLocator_1dX9ddService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Admin\\BlogController:delete' => ['privates', '.service_locator.A2a9FbN', 'get_ServiceLocator_A2a9FbNService', true],
            'App\\Controller\\Admin\\BlogController:edit' => ['privates', '.service_locator.A2a9FbN', 'get_ServiceLocator_A2a9FbNService', true],
            'App\\Controller\\Admin\\BlogController:index' => ['privates', '.service_locator.3Q_vHjc', 'get_ServiceLocator_3QVHjcService', true],
            'App\\Controller\\Admin\\BlogController:show' => ['privates', '.service_locator.A2a9FbN', 'get_ServiceLocator_A2a9FbNService', true],
            'App\\Controller\\BlogController:commentForm' => ['privates', '.service_locator.A2a9FbN', 'get_ServiceLocator_A2a9FbNService', true],
            'App\\Controller\\BlogController:commentNew' => ['privates', '.service_locator.Sd9SChb', 'get_ServiceLocator_Sd9SChbService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.DXcXSsX', 'get_ServiceLocator_DXcXSsXService', true],
            'App\\Controller\\BlogController:postShow' => ['privates', '.service_locator.A2a9FbN', 'get_ServiceLocator_A2a9FbNService', true],
            'App\\Controller\\BlogController:search' => ['privates', '.service_locator.3Q_vHjc', 'get_ServiceLocator_3QVHjcService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.IKb2hHY', 'get_ServiceLocator_IKb2hHYService', true],
            'App\\Controller\\UserController:changePassword' => ['privates', '.service_locator.1d_X9dd', 'get_ServiceLocator_1dX9ddService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Admin\\BlogController::delete' => '?',
            'App\\Controller\\Admin\\BlogController::edit' => '?',
            'App\\Controller\\Admin\\BlogController::index' => '?',
            'App\\Controller\\Admin\\BlogController::show' => '?',
            'App\\Controller\\BlogController::commentForm' => '?',
            'App\\Controller\\BlogController::commentNew' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::postShow' => '?',
            'App\\Controller\\BlogController::search' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::changePassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\BlogController:delete' => '?',
            'App\\Controller\\Admin\\BlogController:edit' => '?',
            'App\\Controller\\Admin\\BlogController:index' => '?',
            'App\\Controller\\Admin\\BlogController:show' => '?',
            'App\\Controller\\BlogController:commentForm' => '?',
            'App\\Controller\\BlogController:commentNew' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:postShow' => '?',
            'App\\Controller\\BlogController:search' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:changePassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
