<?php

namespace Container1Tovr2o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sd9SChbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sd9SChb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sd9SChb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'post' => ['privates', '.errored..service_locator.Sd9SChb.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.Sd9SChb": it references class "App\\Entity\\Post" but no such service exists.'],
        ], [
            'eventDispatcher' => '?',
            'post' => 'App\\Entity\\Post',
        ]);
    }
}
